### ISSUE TITLE
Add ImageReference.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/skaffold-tools-for-java#12]
Copied directly from Jib (https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/image/ImageReference.java).

**Comment by loosebazooka** [comment]
Why would the skaffold plugin need this?

**Comment by coollog** [comment]
This would be used to generate the image reference with tag that's templated into the kubernetes yaml. It could also parse the image reference defined on Jib and process it (like retagging) to use unique references rather than tags.
